name: astrosynth
description: "AstroSynth - AI-Driven Exoplanet Ecosystem Simulator for NASA Space Apps Challenge"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10

  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.3

  # State Management
  provider: ^6.1.2

  # Local Storage
  sqflite: ^2.3.3
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3

  # JSON & Serialization
  json_annotation: ^4.9.0

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3

  # AR & 3D
  # ar_flutter_plugin: ^0.7.3  # Will add when implementing AR feature
  # flutter_gl: ^0.0.21  # Will add when implementing 3D visualization

  # Charts & Visualization
  fl_chart: ^0.68.0

  # UI Components
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

  # Testing
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/
    - assets/data/exoplanets.db
    - assets/data/Exoplanet_FULL.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
