import '../models/planet.dart';

/// Mock planet data for fallback when NASA API is unavailable
/// This ensures the app always has data to display
class MockPlanetData {
  static List<Planet> getMockPlanets() {
    return [
      Planet(
        name: 'Kepler-442 b',
        hostStarName: 'Kepler-442',
        distanceFromEarth: 366.0,
        orbitalPeriod: 112.3,
        radius: 1.34,
        mass: 2.3,
        equilibriumTemperature: 233.0,
        semiMajorAxis: 0.409,
        eccentricity: 0.04,
        stellarSpectralType: 'K',
        stellarTemperature: 4402.0,
        stellarRadius: 0.61,
        stellarMass: 0.61,
        discoveryYear: 2015,
        discoveryMethod: 'Transit',
        habitabilityScore: 85.2,
        biomeType: 'temperate',
      ),
      Planet(
        name: 'Proxima Centauri b',
        hostStarName: 'Proxima Centauri',
        distanceFromEarth: 1.3,
        orbitalPeriod: 11.2,
        radius: 1.07,
        mass: 1.27,
        equilibriumTemperature: 234.0,
        semiMajorAxis: 0.0485,
        eccentricity: 0.02,
        stellarSpectralType: 'M',
        stellarTemperature: 3042.0,
        stellarRadius: 0.154,
        stellarMass: 0.122,
        discoveryYear: 2016,
        discoveryMethod: 'Radial Velocity',
        habitabilityScore: 78.5,
        biomeType: 'tundra',
      ),
      Planet(
        name: 'TRAPPIST-1 e',
        hostStarName: 'TRAPPIST-1',
        distanceFromEarth: 12.1,
        orbitalPeriod: 6.1,
        radius: 0.92,
        mass: 0.62,
        equilibriumTemperature: 251.0,
        semiMajorAxis: 0.028,
        eccentricity: 0.0,
        stellarSpectralType: 'M',
        stellarTemperature: 2566.0,
        stellarRadius: 0.117,
        stellarMass: 0.089,
        discoveryYear: 2017,
        discoveryMethod: 'Transit',
        habitabilityScore: 92.1,
        biomeType: 'ocean',
      ),
      Planet(
        name: 'Kepler-186 f',
        hostStarName: 'Kepler-186',
        distanceFromEarth: 178.5,
        orbitalPeriod: 129.9,
        radius: 1.17,
        mass: 1.71,
        equilibriumTemperature: 188.0,
        semiMajorAxis: 0.356,
        eccentricity: 0.0,
        stellarSpectralType: 'M',
        stellarTemperature: 3755.0,
        stellarRadius: 0.54,
        stellarMass: 0.48,
        discoveryYear: 2014,
        discoveryMethod: 'Transit',
        habitabilityScore: 73.8,
        biomeType: 'ice',
      ),
      Planet(
        name: 'Kepler-452 b',
        hostStarName: 'Kepler-452',
        distanceFromEarth: 430.0,
        orbitalPeriod: 384.8,
        radius: 1.63,
        mass: 5.0,
        equilibriumTemperature: 265.0,
        semiMajorAxis: 1.046,
        eccentricity: 0.0,
        stellarSpectralType: 'G',
        stellarTemperature: 5757.0,
        stellarRadius: 1.11,
        stellarMass: 1.04,
        discoveryYear: 2015,
        discoveryMethod: 'Transit',
        habitabilityScore: 88.4,
        biomeType: 'temperate',
      ),
      Planet(
        name: 'HD 40307 g',
        hostStarName: 'HD 40307',
        distanceFromEarth: 12.8,
        orbitalPeriod: 197.8,
        radius: 2.4,
        mass: 7.1,
        equilibriumTemperature: 277.0,
        semiMajorAxis: 0.6,
        eccentricity: 0.29,
        stellarSpectralType: 'K',
        stellarTemperature: 4956.0,
        stellarRadius: 0.72,
        stellarMass: 0.77,
        discoveryYear: 2012,
        discoveryMethod: 'Radial Velocity',
        habitabilityScore: 65.2,
        biomeType: 'tropical',
      ),
      Planet(
        name: 'Gliese 667 C c',
        hostStarName: 'Gliese 667 C',
        distanceFromEarth: 7.2,
        orbitalPeriod: 28.1,
        radius: 1.54,
        mass: 3.8,
        equilibriumTemperature: 277.0,
        semiMajorAxis: 0.125,
        eccentricity: 0.02,
        stellarSpectralType: 'M',
        stellarTemperature: 3700.0,
        stellarRadius: 0.42,
        stellarMass: 0.31,
        discoveryYear: 2011,
        discoveryMethod: 'Radial Velocity',
        habitabilityScore: 81.7,
        biomeType: 'temperate',
      ),
      Planet(
        name: 'TOI-700 d',
        hostStarName: 'TOI-700',
        distanceFromEarth: 31.1,
        orbitalPeriod: 37.4,
        radius: 1.19,
        mass: 1.72,
        equilibriumTemperature: 269.0,
        semiMajorAxis: 0.163,
        eccentricity: 0.0,
        stellarSpectralType: 'M',
        stellarTemperature: 3480.0,
        stellarRadius: 0.42,
        stellarMass: 0.42,
        discoveryYear: 2020,
        discoveryMethod: 'Transit',
        habitabilityScore: 79.3,
        biomeType: 'ocean',
      ),
      Planet(
        name: '55 Cancri e',
        hostStarName: '55 Cancri',
        distanceFromEarth: 12.6,
        orbitalPeriod: 0.74,
        radius: 2.17,
        mass: 8.63,
        equilibriumTemperature: 2573.0,
        semiMajorAxis: 0.0156,
        eccentricity: 0.0,
        stellarSpectralType: 'G',
        stellarTemperature: 5196.0,
        stellarRadius: 0.943,
        stellarMass: 0.905,
        discoveryYear: 2004,
        discoveryMethod: 'Radial Velocity',
        habitabilityScore: 12.5,
        biomeType: 'volcanic',
      ),
      Planet(
        name: 'K2-18 b',
        hostStarName: 'K2-18',
        distanceFromEarth: 37.0,
        orbitalPeriod: 33.0,
        radius: 2.61,
        mass: 8.92,
        equilibriumTemperature: 265.0,
        semiMajorAxis: 0.143,
        eccentricity: 0.0,
        stellarSpectralType: 'M',
        stellarTemperature: 3503.0,
        stellarRadius: 0.41,
        stellarMass: 0.45,
        discoveryYear: 2015,
        discoveryMethod: 'Transit',
        habitabilityScore: 71.2,
        biomeType: 'ocean',
      ),
      Planet(
        name: 'WASP-12 b',
        hostStarName: 'WASP-12',
        distanceFromEarth: 283.0,
        orbitalPeriod: 1.09,
        radius: 1.9,
        mass: 1.4,
        equilibriumTemperature: 2516.0,
        semiMajorAxis: 0.0229,
        eccentricity: 0.0,
        stellarSpectralType: 'G',
        stellarTemperature: 6360.0,
        stellarRadius: 1.57,
        stellarMass: 1.35,
        discoveryYear: 2008,
        discoveryMethod: 'Transit',
        habitabilityScore: 8.3,
        biomeType: 'volcanic',
      ),
      Planet(
        name: 'HD 189733 b',
        hostStarName: 'HD 189733',
        distanceFromEarth: 19.3,
        orbitalPeriod: 2.22,
        radius: 1.14,
        mass: 1.13,
        equilibriumTemperature: 1201.0,
        semiMajorAxis: 0.0313,
        eccentricity: 0.0,
        stellarSpectralType: 'K',
        stellarTemperature: 5040.0,
        stellarRadius: 0.76,
        stellarMass: 0.82,
        discoveryYear: 2005,
        discoveryMethod: 'Transit',
        habitabilityScore: 15.7,
        biomeType: 'gasGiant',
      ),
      Planet(
        name: 'Kepler-62 e',
        hostStarName: 'Kepler-62',
        distanceFromEarth: 368.0,
        orbitalPeriod: 122.4,
        radius: 1.61,
        mass: 4.5,
        equilibriumTemperature: 270.0,
        semiMajorAxis: 0.427,
        eccentricity: 0.0,
        stellarSpectralType: 'K',
        stellarTemperature: 4925.0,
        stellarRadius: 0.64,
        stellarMass: 0.69,
        discoveryYear: 2013,
        discoveryMethod: 'Transit',
        habitabilityScore: 82.9,
        biomeType: 'ocean',
      ),
      Planet(
        name: 'Kepler-22 b',
        hostStarName: 'Kepler-22',
        distanceFromEarth: 196.0,
        orbitalPeriod: 289.9,
        radius: 2.4,
        mass: 9.1,
        equilibriumTemperature: 262.0,
        semiMajorAxis: 0.849,
        eccentricity: 0.0,
        stellarSpectralType: 'G',
        stellarTemperature: 5518.0,
        stellarRadius: 0.98,
        stellarMass: 0.97,
        discoveryYear: 2011,
        discoveryMethod: 'Transit',
        habitabilityScore: 75.4,
        biomeType: 'ocean',
      ),
      Planet(
        name: 'LHS 1140 b',
        hostStarName: 'LHS 1140',
        distanceFromEarth: 12.5,
        orbitalPeriod: 24.7,
        radius: 1.73,
        mass: 6.65,
        equilibriumTemperature: 230.0,
        semiMajorAxis: 0.0875,
        eccentricity: 0.0,
        stellarSpectralType: 'M',
        stellarTemperature: 3131.0,
        stellarRadius: 0.215,
        stellarMass: 0.146,
        discoveryYear: 2017,
        discoveryMethod: 'Transit',
        habitabilityScore: 87.6,
        biomeType: 'ice',
      ),
      Planet(
        name: 'Ross 128 b',
        hostStarName: 'Ross 128',
        distanceFromEarth: 3.4,
        orbitalPeriod: 9.9,
        radius: 1.1,
        mass: 1.4,
        equilibriumTemperature: 269.0,
        semiMajorAxis: 0.0496,
        eccentricity: 0.0,
        stellarSpectralType: 'M',
        stellarTemperature: 3192.0,
        stellarRadius: 0.197,
        stellarMass: 0.168,
        discoveryYear: 2017,
        discoveryMethod: 'Radial Velocity',
        habitabilityScore: 84.3,
        biomeType: 'temperate',
      ),
      Planet(
        name: 'Kepler-1649 c',
        hostStarName: 'Kepler-1649',
        distanceFromEarth: 91.0,
        orbitalPeriod: 19.5,
        radius: 1.06,
        mass: 1.2,
        equilibriumTemperature: 234.0,
        semiMajorAxis: 0.0649,
        eccentricity: 0.0,
        stellarSpectralType: 'M',
        stellarTemperature: 3240.0,
        stellarRadius: 0.194,
        stellarMass: 0.181,
        discoveryYear: 2020,
        discoveryMethod: 'Transit',
        habitabilityScore: 89.5,
        biomeType: 'tundra',
      ),
      Planet(
        name: 'Kepler-69 c',
        hostStarName: 'Kepler-69',
        distanceFromEarth: 850.0,
        orbitalPeriod: 242.5,
        radius: 1.7,
        mass: 4.8,
        equilibriumTemperature: 299.0,
        semiMajorAxis: 0.64,
        eccentricity: 0.0,
        stellarSpectralType: 'G',
        stellarTemperature: 5638.0,
        stellarRadius: 0.93,
        stellarMass: 0.81,
        discoveryYear: 2013,
        discoveryMethod: 'Transit',
        habitabilityScore: 68.1,
        biomeType: 'tropical',
      ),
      Planet(
        name: 'Teegarden b',
        hostStarName: "Teegarden's Star",
        distanceFromEarth: 3.8,
        orbitalPeriod: 4.9,
        radius: 1.05,
        mass: 1.05,
        equilibriumTemperature: 278.0,
        semiMajorAxis: 0.0252,
        eccentricity: 0.0,
        stellarSpectralType: 'M',
        stellarTemperature: 2904.0,
        stellarRadius: 0.107,
        stellarMass: 0.089,
        discoveryYear: 2019,
        discoveryMethod: 'Radial Velocity',
        habitabilityScore: 86.7,
        biomeType: 'temperate',
      ),
      Planet(
        name: 'Wolf 1061 c',
        hostStarName: 'Wolf 1061',
        distanceFromEarth: 4.3,
        orbitalPeriod: 17.9,
        radius: 1.6,
        mass: 3.41,
        equilibriumTemperature: 223.0,
        semiMajorAxis: 0.084,
        eccentricity: 0.11,
        stellarSpectralType: 'M',
        stellarTemperature: 3380.0,
        stellarRadius: 0.307,
        stellarMass: 0.294,
        discoveryYear: 2015,
        discoveryMethod: 'Radial Velocity',
        habitabilityScore: 70.2,
        biomeType: 'ice',
      ),
    ];
  }

  /// Generate additional mock planets with variations
  static List<Planet> generateAdditionalMockPlanets(int count) {
    final List<Planet> mockPlanets = [];
    final basePlanets = getMockPlanets();

    for (int i = 0; i < count; i++) {
      final basePlanet = basePlanets[i % basePlanets.length];
      final variation = (i / basePlanets.length).floor() + 1;

      mockPlanets.add(
        Planet(
          name: '${basePlanet.name} ${String.fromCharCode(97 + variation)}',
          hostStarName: basePlanet.hostStarName,
          distanceFromEarth:
              basePlanet.distanceFromEarth! * (0.8 + (variation * 0.2)),
          orbitalPeriod: basePlanet.orbitalPeriod! * (0.9 + (variation * 0.15)),
          radius: basePlanet.radius! * (0.85 + (variation * 0.2)),
          mass: basePlanet.mass! * (0.8 + (variation * 0.3)),
          equilibriumTemperature:
              basePlanet.equilibriumTemperature! * (0.95 + (variation * 0.1)),
          semiMajorAxis: basePlanet.semiMajorAxis,
          eccentricity: basePlanet.eccentricity,
          stellarSpectralType: basePlanet.stellarSpectralType,
          stellarTemperature: basePlanet.stellarTemperature,
          stellarRadius: basePlanet.stellarRadius,
          stellarMass: basePlanet.stellarMass,
          discoveryYear: basePlanet.discoveryYear,
          discoveryMethod: basePlanet.discoveryMethod,
          habitabilityScore:
              basePlanet.habitabilityScore! * (0.85 + (variation * 0.2)),
          biomeType: basePlanet.biomeType,
        ),
      );
    }

    return mockPlanets;
  }
}
